### ISSUE TITLE
Hacktoberfest: Make it easier to install

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/easydns-restapi-cli#2]
# Hacktoberfest:  Make it easier to install

Currently, there's no instruction on how to install our CLI . As such, we need to provide users the ability to easily install our CLI. For example:

```
# Installs the CLI globally.
$ make install

# Uninstall the CLI.
$ make uninstall
```

#### References: 
- https://github.com/tuladhar/set-brightness/blob/main/Makefile

- - -
Stay Safe & Happy Hacking,
Puru

**Comment by liisberg** [comment]
I would like to help out with this, assign it to me please.

**Comment by RajSolai** [comment]
I made the changes, by the way your cli looks great #3

**Comment by tuladhar** [comment]
Thanks @RajSolai. I've added some comments, please check.

**Comment by tuladhar** [comment]
Thanks @RajSolai, closing the issue. And thanks @liisberg, there's other issues you can work on, please do check it out.
