### ISSUE TITLE
Hacktoberfest: Add description in CLI usage

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/easydns-restapi-cli#4]
# Hacktoberfest: Add description in CLI usage

### Acceptance Criteria
- Add the following description in CLI usage, such that when running `--help` it shows the description. 
> A command-line tool for managing (create/update) EasyDNS DNS records using easyDNS rest API.

#### Language: Python

- - - 
Stay Safe & Happy Hacking,
Puru

**Comment by dynamo63** [comment]
I would like to be assigned to this task :yum:

**Comment by tuladhar** [comment]
Sure @dynamo63. Assigned.
