### ISSUE TITLE
Hacktoberfest: Github workflow to build release binary

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/easydns-restapi-cli#5]
# Hacktoberfest: Github workflow to build release binary

We want the project to utilize Github Actions to automatically build the release binary.

### Acceptance Criteria
- Create a Github Workflow to build the binary release.

Reference:
- https://github.com/tuladhar/easydns-restapi-cli/tree/1.2#build-from-source
- https://docs.github.com/en/free-pro-team@latest/actions

### Difficulties: Intermediate

- - -

Stay safe & Happy Hacking
Puru

**Comment by shilangyu** [comment]
Sure I can do that. For all three platforms? windows/macos/linux

**Comment by tuladhar** [comment]
Thanks @shilangyu. Yes, I think Github Actions supports all three OS builds. I've assigned the issue to you.
